kind: Service
apiVersion: v1
metadata:
  name: bluebank-sqldata2-service
  labels:
    app: bluebank-sqldata2
spec: 
  clusterIP: 10.96.1.3 
  ipFamilies:
  - IPv4
  ports:
  - name: bluebank-sqldata2
    port: 6432
    nodePort : 31432 
  #type: LoadBalancer
  type: NodePort
  selector:
   app: bluebank-sqldata2