apiVersion: v1
kind: Service
metadata:
  name: bluebank-app-front-service
  labels:
    app: bluebankappfront
spec:
  selector:
   app: bluebankappfront
  #type: NodePort
  type: LoadBalancer
  ports:
   - port: 4200
     targetPort: 81
     #nodePort: 30100